plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '8.3.0'
}

project.version = 'v1.2.2'
ext.applicationName = 'RealmShark'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

project.ext.lwjglVersion = "3.3.1"
project.ext.jomlVersion = "1.10.5"

switch (org.gradle.internal.os.OperatingSystem.current()) {
    case org.gradle.internal.os.OperatingSystem.MAC_OS:
        project.ext.lwjglNatives = "natives-macos"
        break
    case org.gradle.internal.os.OperatingSystem.WINDOWS:
        project.ext.lwjglNatives = "natives-windows"
        break
}

repositories {
    mavenCentral()
    maven { url = "https://s01.oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    implementation 'com.ardikars.pcap:pcap-spi:1.4.2'
    implementation 'com.ardikars.pcap:pcap-jdk7:1.4.2'
    implementation 'com.google.code.gson:gson:2.9.1'
    implementation 'com.google.flatbuffers:flatbuffers-java:23.5.26'
}

application {
    mainClass = 'realmshark.RealmShark'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'realmshark.RealmShark'
        )
    }
}

// Ugly solution to get version into source.
tasks.register('generateSources') {
    doFirst {
        def srcFile = new File(file("$buildDir/../src/main/java/" + applicationName.toLowerCase() + "/version"), "Version.java")
        srcFile.parentFile.mkdirs()
        srcFile.write("""package """ + applicationName.toLowerCase() + """.version;
/**
 * Don't edit this class. It's a gradle class to grab version from the build.gradle
 */
public class Version {
    public static final String VERSION = "$project.version";
}

""")
    }
}

tasks.named('compileJava') {
    dependsOn 'generateSources'
    source tasks.named('generateSources').get().outputs.files, sourceSets.main.java
}

shadowJar {
    manifest {
        attributes 'Main-Class': 'realmshark.RealmShark'
    }
    archiveFileName = "${applicationName}-${project.version}.jar"
}
